Friend request button [PAR-78]
ParaLibrary/paralibrary-frontend pull request #35
Opened 2020-05-15 18:54 UTC by Hashiphoto

Placed the button on the library page and friend library page. The button changes appearance and function depending on what that person's status is relative to the current user.

2020-05-15 20:01 UTC, Hashiphoto commented
Just realized it inconsistently breaks. I'll request review again later once I've fixed it

2020-05-15 20:10 UTC, Hashiphoto commented
Issue has been fixed. I'll post some screenshots in Teams of what the UI looks like

2020-05-16 01:13 UTC, lemniscate8 requested changes
Just had some small suggestions. I can see what you meant in stand up today. The deeper you go the harder it is to see how to keep state the same locally and on the server without forcing a refresh. Not sure the best way to do that though since I think we've been dealing with it in a lot of different ways across the project.

2020-05-16 01:13 UTC, lemniscate8 commented on src/FriendshipResponseButtons.tsx
> +  useEffect(() => {}, []);
Leftover `useEffect`

2020-05-16 01:13 UTC, lemniscate8 commented on src/FriendshipStatusButton.tsx
> +        <Button variant="info" disabled onClick={requestFriendship}>
If this button is always disabled it doesn't need an onClick property.

2020-05-16 01:13 UTC, lemniscate8 commented on src/FriendshipStatusButton.tsx
> +    <PaddedDiv>
If only one of these buttons can appear on the page, maybe use a switch statement or a sequence of if-else statements.

2020-05-16 01:13 UTC, lemniscate8 commented on src/FriendshipStatusButton.tsx
> +  rowitem?: User;
I only used these props because I thought this button might be used in the autotable, but if it isn't, you could rename this property to something more specific and make it required (without the ?). The checks in line 23 an a lot of other places wouldn't be necessary.

2020-05-16 01:13 UTC, lemniscate8 commented on src/FriendshipStatusButton.tsx
> +const FriendshipRequestButton: React.FC<FRBProps> = ({
Maybe rename to FriendshipStatusButton?

2020-05-16 01:13 UTC, lemniscate8 commented on src/FriendshipResponseButtons.tsx
> +const FriendRequestButtons: React.FC<ButtonGroupProps> = ({
Maybe this isn't the place for this (we can always refactor later), but this component could probably be split into two independent buttons.

2020-05-16 01:13 UTC, lemniscate8 commented on src/FriendshipStatusButton.tsx
> +    onClick({ ...friend, status: "requested" });
Should this be set even if the fetch fails? The pattern we've been using usually puts this sort of behavior inside a `.then` call.

2020-05-16 19:10 UTC, Hashiphoto commented
Addressed review comments. I moved Accept and Reject buttons into separate files, set the state of the button to "requested" only after the fetch completes, and implemented various other suggestions as well.

2020-05-16 19:32 UTC, lemniscate8 approved these changes
Looks good!

2020-05-16 19:58 UTC, merged